# MongoDB settings
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: student_database

# Server settings
server:
  port: 5000
  connection-timeout: 100
  contextPath: /api/v1